---
name: fte
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.11
  - pip

  # Dependencies
  - pytask
  - pandas
  - numpy
  - jupyterlab
  - scikit-learn
  - tqdm
  - matplotlib

  # Misc
  - black
  - nb_black
  - ipython
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - pdbpp
  - setuptools_scm
  - toml
  - click
  - pip:
      - -e .
      - blackcellmagic
